name: Deploy to IBM Cloud

on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - run: |
        wget -q https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip
        unzip -o v2ray-linux-64.zip "v2ray" "v2ctl" "geosite.dat" "geoip.dat" 
        rm -rf v2ray-linux-64.zip
        chmod 700 v2ray v2ctl
        mv v2ray yar2v
        touch `date +%Y%m%d%H%M%S`
        cat > config.json << EOF
        {
          "inbounds": [
            {
              "port": 8080,
              "protocol": "vmess",
              "settings": {
                "clients": [
                  {
                    "id": "${{ secrets.CF_UUID_IBM }}",
                    "alterId": 4
                  }
                ]
              },
              "streamSettings": {
                "network":"ws",
                    "wsSettings": {
                        "path": "${{ secrets.CF_PATH_IBM }}"
                    }                
              }
            }
          ],
          "outbounds": [
            {
              "protocol": "freedom",
              "settings": {}
            }
          ]
        }
        EOF
        
        VMESSCODE=$(base64 -w 0 << EOF
          {
            "v": "2",
            "ps": "${{ secrets.IBM_APP_NAME }}",
            "add": "${{ secrets.IBM_APP_NAME }}.us-south.cf.appdomain.cloud",
            "port": "443",
            "id": "${{ secrets.CF_UUID_IBM }}",
            "aid": "4",
            "net": "ws",
            "type": "none",
            "host": "",
            "path": "{{ secrets.CF_PATH_IBM }}",
            "tls": "tls"
          }
          EOF
        )
        
        echo vmess://${VMESSCODE} > vmess.url
        
        cat > manifest.yml << EOF
        ---
        applications:
        - name: ${{ secrets.IBM_APP_NAME }}
          memory: 128M
          disk_quota: 1G
          random-route: true
          buildpacks:
          - binary_buildpack
        EOF
        
        cat > Procfile << EOF
        web: ./yar2v
        EOF
    
    - uses: citizen-of-planet-earth/cf-cli-action@v1
      with:
        cf_api: https://api.us-south.cf.cloud.ibm.com
        cf_username: ${{ secrets.CF_USER_IBM }}
        cf_password: ${{ secrets.CF_PASSWORD_IBM }}
        cf_org: ${{ secrets.CF_ORG_IBM }}
        cf_space: ${{ secrets.CF_SPACE_IBM }}
        command: >
          push ${{ secrets.IBM_APP_NAME }}
          
